services:
  - type: web
    name: syb-zone-monitor
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: SYB_API_KEY
        sync: false
      - key: POLLING_INTERVAL
        value: "60"
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8080"
    autoDeploy: true
    healthCheckPath: /health