#!/usr/bin/env python3
"""Verify WhatsApp credentials on Render by checking logs."""

print("📋 WhatsApp Configuration Checklist for Render:")
print("=" * 60)
print()
print("1. Go to Render Dashboard: https://dashboard.render.com")
print("2. Navigate to your service: syb-offline-alarm")
print("3. Click on 'Environment' tab")
print()
print("✅ Verify these environment variables are set:")
print("   - WHATSAPP_PHONE_NUMBER_ID = 742462142273418")
print("   - WHATSAPP_ACCESS_TOKEN = (your new token)")
print("   - WHATSAPP_ENABLED = true")
print()
print("4. If any are wrong, update them and click 'Save Changes'")
print("5. After saving, click 'Manual Deploy' → 'Clear build cache & deploy'")
print()
print("📱 To test WhatsApp manually:")
print("   Since the web endpoints seem inaccessible, the service might be")
print("   running but not exposing the web interface properly.")
print()
print("💡 Alternative: Check if automatic notifications are working")
print("   by monitoring the Render logs when a zone goes offline.")